# Catppuccin Mocha Alacritty Theme

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.normal]
black   = "#45475a"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#bac2de"

[colors.bright]
black   = "#585b70"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#a6adc8"

# Optional (recommended): dim colors
[colors.dim]
black   = "#313244"
red     = "#e64553"
green   = "#89d18a"
yellow  = "#e6d087"
blue    = "#74a2e8"
magenta = "#d8a9d1"
cyan    = "#7cc8bc"
white   = "#9399b2"

# ----- Window Settings -----

[window.dimensions]
columns = 70
lines = 17

[window.padding]
x = 70
y = 70

# ----- Font -----

[font]
size = 10.0

