conky.config = {
    alignment = 'top_left',
    background = false,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = '#e6e9ef',
    default_outline_color = '#e6e9ef',
    default_shade_color = '#cdd6f4',
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    font = 'DejaVu Sans Mono:size=12',
    gap_x = 0,
    gap_y = 0,
    minimum_height = 5,
    minimum_width = 5,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_wayland = false,
    out_to_x = true,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'normal',
    own_window_hints = 'undecorated,sticky,below,skip_taskbar,skip_pager',
    show_graph_range = false,
    show_graph_scale = false,
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true,
    own_window_colour = '#DCE0E8',   -- Catppuccin Mocha background
    own_window_argb_visual = false,
}

-- Variables: https://conky.cc/variables
conky.text = [[
                             
${color #45475a}
${offset 20}${color #f3978b}${font Nasalization:size=44}${time %I:%M}${font}
${offset 20}${font Nasalization:size=20}${color #f3978b}${time %p}${font}
# --- Today (highlighted, big number + shifted day/month) ---
${offset 20}${font Nasalization:size=20}${color #c0ac81}${time %d}${font}
${offset 20}${font Nasalization:size=20}${color #c0ac81}${time %A}${font}
${offset 20}${font Nasalization:size=24}${color #c0ac81}${time %B}${font}

${font Nasalization:size=15}${font Nasalization:size=13}
${offset 20}${color #79819b}${exec whoami}
${offset 20}${color #79819b}${execi 300 awk -F= '/^PRETTY_NAME=/{gsub(/"/,"",$2); sub(/\s*\(.*/,"",$2); print $2}' /etc/os-release}
${offset 20}${color #79819b}${execi 300 echo $XDG_CURRENT_DESKTOP}


${offset 20}${font Nasalization:size=13}${color #79819b}CPU:        ${goto 90}${cpu cpu0}%${font}
${offset 20}${font Nasalization:size=13}${color #79819b}RAM:        ${goto 90}${memperc}%${font}
${offset 20}${font Nasalization:size=13}${color #79819b}Disk:       ${goto 90}${fs_used_perc /}%${font}

${offset 20}${font Nasalization:size=10}${color #79819b}CPU Temp:   ${goto 130}${exec sensors | grep 'Package id 0:' | awk '{print $4}'}${font}
${offset 20}${font Nasalization:size=10}${color #79819b}Download:   ${goto 130}${downspeed wlo1} KB/s${font}
${offset 20}${font Nasalization:size=10}${color #79819b}Upload:     ${goto 130}${upspeed wlo1} KB/s${font}

${offset 20}${font Nasalization:size=10}${color #79819b}Uptime: ${uptime}${font}

]]

